
name: Publish Website to CPanel
on:
  push:
    branches:
      - master
jobs:
  FTP-Deploy-Action:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
    - id: gcloud
    -  uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
    +  uses: google-github-actions/setup-gcloud@master
    #   with:
    #     fetch-depth: 2
    # - name: Dating
    #   uses: Tofik100/Dating@master
      with:
        ftp-server: ${{ secrets.FTP_SERVER }}
        ftp-username: ${{ secrets.FTP_USERNAME }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}
